services:
  ollamadb:
    image: ghcr.io/frefrik/ollama-models-api:latest
    container_name: ollama-models-api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - cloudflared
    env_file:
      - .env
    volumes:
      - ${SQLITE_DATABASE_PATH:-./ollama_models.db}:/code/ollama_models.db
    environment:
      - ENVIRONMENT=production

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-ollamadb
    restart: always
    command: tunnel --no-autoupdate run
    env_file:
      - cloudflared.env
